[terminal.shell]
program = "zellij"
args = [
  # "attach",
  # "--create",
  # "general",
  "options",
  "--default-shell",
  "nu"
  # "-l",
  # "-c",
  # "zellij attach --index 0 || zellij"
]

[window]
startup_mode = "Maximized"

[terminal]
