[shell]
# program = "/bin/zsh"
# args = [
#   "-l",
#   "-c",
#   "zellij attach --index 0 || zellij"
# ]
program = "/opt/homebrew/bin/zellij"
args = [
  "options",
  "--default-shell",
  "/opt/homebrew/bin/nu"
]

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[font]
size = 15
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
