[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "json"
# language-servers = [ "vscode-json-language-server" ]
formatter = { command = "prettier", args = [ "--parser", "json" ] }
auto-format = true

[[language]]
name = "yaml"
# language-servers = [ "vscode-json-language-server" ]
formatter = { command = "prettier", args = [ "--parser", "yaml" ] }
auto-format = true
